In [1]:
from google.colab import files


In [2]:
uploaded = files.upload()

Saving Folds5x2_pp.xlsx to Folds5x2_pp.xlsx


In [4]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "Folds5x2_pp.xlsx" with length 2029440 bytes


In [5]:
import numpy as np
import pandas as pd


In [7]:
df=pd.read_excel('Folds5x2_pp.xlsx')

In [9]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [10]:
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [11]:
df_with_features=df.drop("PE",axis='columns')

In [14]:
df_with_features.shape

(9568, 4)

In [23]:
df_with_electricpower=df['PE']
df_with_electricpower.shape

(9568,)

In [16]:
### to predict EP using general equation method
# EP=m1*V  +   m2*AP+  m3*RH + m4* AT  +m5


In [24]:
A=df_with_features.to_numpy(dtype ='float32')
B=df_with_electricpower.to_numpy(dtype ='float32')


In [28]:
B=B.reshape(9568,1)

In [31]:
A_1= np.c_[np.ones((9568, 1)), df_with_features]

In [48]:
#### using least square method

m2 = np.linalg.inv(A_1.T.dot(A_1)).dot(A_1.T).dot(B)
m2




array([[ 4.54609275e+02],
       [-1.97751312e+00],
       [-2.33916404e-01],
       [ 6.20829435e-02],
       [-1.58054115e-01]])

In [49]:
#### check for answer using least square method...the answer was 463 and we got 444 for first row
A_1[1,:].T.dot(m2)


array([444.07736624])

In [52]:
### to check for slope and bias using pseudo inverse

m3 =np.linalg.pinv(A_1).dot(B)
m3

array([[ 4.54609275e+02],
       [-1.97751312e+00],
       [-2.33916404e-01],
       [ 6.20829435e-02],
       [-1.58054115e-01]])